name: pb
favicon: null
layout_spectrum: 0.82931
typography_spectrum: 0.2142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#006699'
    - '#333333'
    - '#b89561'
    - '#97564e'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.1466485313139856
purpose: []
